app = "asataxi"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PYTHONUNBUFFERED = "1"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"
